# Generated by Django 3.2.3 on 2022-12-15 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210606_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateField(default=datetime.date(2022, 12, 15)),
        ),
    ]
