# Generated by Django 4.1.7 on 2023-04-07 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_customer_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(default=datetime.date(2023, 4, 7)),
        ),
    ]
