# Generated by Django 4.1.4 on 2023-08-26 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_customer_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(default=datetime.date(2023, 8, 26)),
        ),
    ]
